services:
  - type: web
    name: shl-assessment-recommendation-system
    env: python
    region: singapore 
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port $PORT --server.address 0.0.0.0
    autoDeploy: true
